### ISSUE TITLE
wrong link for noisy channel

### ISSUE THREAD

**Issue by Sandy4321** [avidale/weirdMath#2]
https://github.com/avidale/weirdMath/blob/master/nlp/abbreviation_spellchecker_english.ipynb

The whole construction is called a noisy channel model.
http://web.stanford.edu/~jurafsky/slp3/5.pdf

may you add correct link pls

**Comment by avidale** [comment]
The SLP website is evolving, so I think I'll just make the link to the main page.

**Comment by Sandy4321** [comment]
so what is correct link 
The whole construction is called a noisy channel model

**Comment by Sandy4321** [comment]
is it 
http://web.stanford.edu/~jurafsky/slp3/B.pdf
CHAPTER
B
Spelling Correction and the
Noisy Channel

**Comment by avidale** [comment]
Yes, it is. 
In a previous version of the book, it was one of major chapters; now it is moved into an appendix.

**Comment by Sandy4321** [comment]
thanks
